camera_location: [2, 0, 1]
car_dimensions: [4, 2, 2]
color_fov: [69, 55] # [horiz, vert]
depth_fov: [72, 49] # [horiz, vert]
dimensions: [540, 960] # [rows, cols]
scope: [20, 2] # [distance, height]
tracking_imgs: 2
prediction_imgs: 2
min_object_area: .005 # 2500 / 540 * 960